### ISSUE TITLE
I have a good idea

### ISSUE THREAD

**Issue by istrwei** [hwding/pdf-unstamper#1]
Since it can be removed part of the logo, can be added to the logo!

**Comment by hwding** [comment]
Do you mean adding watermarks to a PDF file?

**Comment by istrwei** [comment]
yes！

**Comment by hwding** [comment]
Good indeed!  
However, there are already several implementations to the functionality you proposed, such as https://coderanch.com/how-to/javadoc/itext-2.1.7/com/lowagie/text/pdf/PdfStamper.html.   
Creating a new repository for pdf-stamper may be a good idea, stamp not only text mark but picture!  
If you have the motivation to create a new pdf-stamper tool, I’m glad to help!

**Comment by istrwei** [comment]
thank you very much!
