### ISSUE TITLE
[Bug / Performace / Enhancement ] Brief description here

### ISSUE THREAD

**Issue by chri-z** [hwding/pdf-unstamper#10]
nothing working

**Comment by hwding** [comment]
Plz provide a more detailed desc., attach file or link and describe the issue.

**Comment by c-void** [comment]
@hwding 

I just tried to remove watermarks from this  [File](https://gitlab.com/c-void/xfiles/raw/8190bdf68c15158425c9072c59ec9bfc8febc852/docs/Q/S1/be100/BE100_2016_AUG.pdf?inline=false)

It have a image watermark and a text watermark , but I wasn't able to remove the text even

If there any other solution exist ,please link me :blush:

**Comment by hwding** [comment]
![图片](https://user-images.githubusercontent.com/15152879/73131997-ab5fd580-404f-11ea-81a9-c346cb4b6ca6.png)

Enlarged stamp.
Seems that this waster stamp is not text but some kind of pic, it cannot be recognised by text match.
