### ISSUE TITLE
使用没效果

### ISSUE THREAD

**Issue by IAmYuanZhao** [hwding/pdf-unstamper#3]
您好，我使用了你的jar包，但是执行之后没有去除文字，麻烦帮看下~

**Comment by daiyan299** [comment]
我也有相同的问题，pdf文件很大，是否可以直接上传？

**Comment by hwding** [comment]
可以提供下网盘的外链。

Best regards,
hwding.

# Sent from mobile device

**Comment by daiyan299** [comment]
链接: https://pan.baidu.com/s/1GI2heNEQO7KSwHEeb6odig 提取码: 7y62
感谢~

**Comment by daiyan299** [comment]
执行命令之后java 的线程是有读写硬盘操作的，而且也有较多的cpu占用，输出文件夹也可以看到有文件生成，但是生成的文件和源文件是一样的。
系统版本：
windows 10 10.0.17134 版本 17134

**Comment by hwding** [comment]
@daiyan299 好的，这些信息应该够了。

**Comment by daiyan299** [comment]
感谢~

**Comment by hwding** [comment]
@daiyan299 
工具已经适配了这种文件加水印的方式，将在下一版本发布这个增强功能，麻烦注意关注下。
再次感谢反馈。

参数不变：
`java -jar unstamper.jar -i example.pdf -o example.unstamped.pdf -k 微信公众号 学习共享`

**Comment by daiyan299** [comment]
OK，感谢感谢，不过不知道你是不是用的这个方法，这个水印可以在内容里面直接检索objectx对象，然后删除。

On Feb 19, 2019, at 2:08 PM, hwding <notifications@github.com<mailto:notifications@github.com>> wrote:


@daiyan299<https://github.com/daiyan299>
工具已经适配了这种文件加水印的方式，将在下一版本发布这个增强功能，麻烦注意关注下。
再次感谢反馈。

参数不变：
java -jar unstamper.jar -i example.pdf -o example.unstamped.pdf -k 微信公众号 学习共享

**Comment by hwding** [comment]
@daiyan299  
我用的是先识别页面MarkedContent里面的TextPosition，然后在处理COSString的过程中顺便把相应的Token标记下来，最后更新页面的时候再一并移除。

你说的这个方法我也看看，学习下。

**Comment by daiyan299** [comment]
这些文件出错，还有一些其他的文件也报错的，有哆嗦模式可以看一下么
错误类型：
[Processor] Error processing certain page of 'LOVE咖啡.pdf', skipping
这一条重复了很多次，出错条数和页面数相同
错误文件：
链接: https://pan.baidu.com/s/1sjmpIPeKRavIHQK-FDUsNg 提取码: mi28
链接: https://pan.baidu.com/s/1LcaJqPzHgMgKqDinW2xhlw 提取码: x284

**Comment by hwding** [comment]
@daiyan299 我先看下原因，下一版看看能不能提供异常的verbose。

**Comment by daiyan299** [comment]
好的，麻烦了

**Comment by hwding** [comment]
@daiyan299 上述问题已经解决，非常感谢你的反馈。

另外新的问题建议新创建issue，这样利于跟踪，并且不会打扰在旧issue上的人。
