### ISSUE TITLE
[Enhancement]  PDF contains an encryption dictionary, please remove it with setAllSecurityToBeRemoved() ...

### ISSUE THREAD

**Issue by leewi9** [hwding/pdf-unstamper#6]
**Describe the issue**

![image](https://user-images.githubusercontent.com/10832544/53227744-1d9a9e00-36ba-11e9-95e3-bb66c0d05740.png)

**Version**
0.2.3

**Arguments**
`java -jar pdf-unstamper.jar -c -i '风吹江南之互联网金融_陈宇.pdf' -k '更多资料请关注我的网易博客http://ntccy2009.blog.163.com/'`

**Expected behavior**
A brief description of what you expected to happen.

**Original file(s)**

original file download link: https://pan.baidu.com/s/15qH_ahkDTKnn8rYTE1UpjA

**Comment by daiyan299** [comment]
这个提示有加密，去除加密后再次尝试

**Comment by hwding** [comment]
Informed，这个我先看看工具能不能去除简单的限制。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hwding** [comment]
@leewi9 好了，不着急的话下个版本会带着这个fix发布。
