### ISSUE TITLE
[Bug] 去除的字符含有空格，貌似会误删很多文字

### ISSUE THREAD

**Issue by leewi9** [hwding/pdf-unstamper#7]
比如这个 “Download from Wow! eBook <www.wowebook.com>”

http://download.library1.org/main/833000/4fd7f0dd7f5eddb192ed97af0c4eb445/Peter%20Harrington%20-%20Machine%20Learning%20in%20Action-Manning%20Publications%20%282012%29.pdf

**Comment by hwding** [comment]
@leewi9 完整的命令输入（带参数）贴一下吧。

**Comment by leewi9** [comment]
```sh
java -jar pdf-unstamper.jar -c -i "pdf1" -o "pdf2" -k "Download from Wow! eBook <www.wowebook.com>"
```

**Comment by hwding** [comment]
@leewi9 `java -jar pdf-unstamper.jar` 贴一下版本号吧，我这里貌似没发现有错位。

**Comment by hwding** [comment]
麻烦把处理后有问题的文件上传或者外链发我，然后说明下有问题的页数吧。

最新版本是0.2.5。

Best regards,
hwding.

# 📧 sent with mobile device

**Comment by hwding** [comment]
@leewi9 我这边比对了30页，目前没发现问题，最新版本是0.2.5。
你可以把问题页面截图并告知页号，或者直接在这里上传修改后有问题的文件，外链也可以。

**Comment by hwding** [comment]
Closed for no responce for a long time.
