### ISSUE TITLE
This pdf can not remove.

### ISSUE THREAD

**Issue by audiorecorder** [hwding/pdf-unstamper#8]
https://www.dropbox.com/s/dl/7vm0o0neefowljt/test_watermark.pdf
"iLovePDF" text do not remove.
This file just has created from PDF tool site with text-type waterrmark.

**Comment by hwding** [comment]
Plz provide your pdf tool site link.

**Comment by 1w3j** [comment]
Using `sed -i test_watermark.pdf -e "/iLovePDF//`" on the uncompressed pdf works, apply sed to uncompressed pdfs
