### ISSUE TITLE
cnki下载的文献下面的水印是否可以删除

### ISSUE THREAD

**Issue by chunchu** [hwding/pdf-unstamper#9]
万方、维普数据库下载的文献就没有水印

**Comment by hwding** [comment]
@chunchu 麻烦在回复上传CNKI的个文件样本，或这给出文件下载地址。

**Comment by chunchu** [comment]
PDF最下方的那行就是

[生物玻璃应用于拔牙位点保存术的临床研究进展.pdf](https://github.com/hwding/pdf-unstamper/files/3236991/default.pdf)

**Comment by hwding** [comment]
![图片](https://user-images.githubusercontent.com/15152879/73132069-e282b680-4050-11ea-9233-e0b880e6d287.png)

放大看了一下貌似不是纯文字，因此无法使用文字匹配的方式进行识别。
